import '../app/globals.css'

export const metadata = {
  title: 'ラヴィ  アズラ  プトラ',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="text-yellow-300 bg-pink-500 mb-5 text-2xl text-center">
          <p>
            日本でプログラマーになれるといいですね
          </p>
        </header>
        {children}
        <footer>
          <p className="bg-green-200 text-black mt-5 text-2xl text-center">
            夢 を 諦めないで
          </p>
        </footer>
      </body>
    </html>
  )
}
